Sprint 13
tarasovEgor/java-shareit pull request #1
Opened 2023-09-23 22:32 UTC by tarasovEgor

2023-09-25 10:59 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private ItemServiceImpl itemServiceImpl;
Здесь нужно указать тип  ItemService itemService (т.е. базовый интерфейс), спринг по аннотации @Service найдет, что для типа  ItemService есть реализация  ItemServiceImpl и при создании класса ItemController подставит экземпляр  ItemServiceImpl в поле itemService.

2023-09-25 11:02 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +    private ItemService itemService;
А зачем здесь ссылка на класс самого себя? Это поле лишнее

2023-09-25 11:04 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemDaoImpl.java
> +public class ItemDaoImpl implements ItemDao, ItemService {
Dao не может реализовывать Service. Обычно Dao это поле в классе реализации Service.

2023-09-25 11:09 UTC, VadimZharkov requested changes
В пакете item нужно разобраться с зависимостями между зависимостями Controller, Dao и Service

2023-09-25 18:36 UTC, tarasovEgor commented
Привет, переписал код, вроде сейчас нормально с зависимостями. Не совсем понимаю только, зачем нам для Item создавать отдельный интерфейс ItemService и его реализацию? Разве нельзя по аналогии с юзером сделать один класс для сервиса?

2023-09-26 06:44 UTC, VadimZharkov commented
> Привет, переписал код, вроде сейчас нормально с зависимостями. Не совсем понимаю только, зачем нам для Item создавать отдельный интерфейс ItemService и его реализацию? Разве нельзя по аналогии с юзером сделать один класс для сервиса?

Привет, можно не создавать интерфейс и сделать просто класс с реализацией. Могу сказать что так принято для сервисов, сначала интерфейс, затем реализация. В данном проекте не видна выгода, но в проектах с более сложной архитектурой, определение интерфейса может быть в одном модуле, а реализация в другом и тогда без разделения не обойтись. И сейчас вас просто приучают не делать по простому, а делать так как скорее всего вы встретите на реальном проекте.

2023-09-26 06:49 UTC, VadimZharkov approved these changes

2023-10-02 15:44 UTC, merged