feat: bookings and comments added
tarasovEgor/java-shareit pull request #2
Opened 2023-10-16 15:15 UTC by tarasovEgor

2023-10-17 09:19 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public Booking getBookingById(@PathVariable long bookingId,
Лучше чтобы контроллер наружу отдавал только Dto, а не саму модель.

2023-10-17 09:26 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/dto/ItemWithBookingDto.java
> +    private Long id;
Т.к. поля не изменяемые, то лучше сделать их final

2023-10-17 09:27 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +        for (Comment c : comments) {
Попробуй сделать не циклом, а с помощью стримов

2023-10-17 09:34 UTC, VadimZharkov requested changes
Привет, можно улучшить

2023-10-19 22:15 UTC, tarasovEgor commented
Привет, сильно задержался, но, вроде, теперь выглядит лучше, во всех контроллерах поменял возвращаемый тип на dto, метод в CommentMapper переписал. Подскажи еще, пожалуйста, у меня в репозиториях большинство методов написаны в ручную через @Query, нормально ли это или лучше все-таки стараться писать через запросные-методы?

2023-10-20 08:09 UTC, VadimZharkov commented
> Привет, сильно задержался, но, вроде, теперь выглядит лучше, во всех контроллерах поменял возвращаемый тип на dto, метод в CommentMapper переписал. Подскажи еще, пожалуйста, у меня в репозиториях большинство методов написаны в ручную через @query, нормально ли это или лучше все-таки стараться писать через запросные-методы?

Привет, абсолютно нормально. Нужно и так и так уметь.  @query порой наглядней, потому как видишь сам SQL, запросные методы при большом кол-ве параметров выглядят слишком многословными.
Я придерживаюсь след. правила при простых запросах -  запросные-методы, при сложных - @query

2023-10-20 08:10 UTC, VadimZharkov approved these changes

2023-10-20 08:42 UTC, VadimZharkov approved these changes

2023-10-21 20:20 UTC, tarasovEgor commented
Хорошо, спасибо, учту)

2023-10-23 14:34 UTC, merged