feat: item-requests, mock-tests added
tarasovEgor/java-shareit pull request #3
Opened 2023-11-26 21:37 UTC by tarasovEgor

2023-11-30 11:30 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public List<BookingDto> getAllBookingsByBooker(@RequestParam(required = false, defaultValue = "0") int from,
required = false, defaultValue = "0" Здесь одно противоречит другому

2023-11-30 11:33 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +        switch (Objects.requireNonNull(status)) {
Нужно перевести в перечислимое и его использовать

2023-11-30 11:36 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +            if (size == 2) size = 1;
Не понял логику, можешь прояснить?

2023-11-30 11:45 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingDto> getAllBookingsByBooker(String state, long bookerId, Integer from, Integer size);
Вместо Integer можно int

2023-11-30 11:47 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
>  public class ErrorHandler {
Нужно добавить обработку Throwable в статус 500

2023-11-30 11:52 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/dao/impl/ItemDaoImpl.java
> +//package ru.practicum.shareit.item.dao.impl;
Закомментированного кода в решении не должно быть

2023-11-30 11:59 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
Запросы к БД в маппере должны отсутствовать. Если сущность нужно дозаполнить значениями других сущностей, то лучше это сделать в классе сервисе. В маппере не должно быть зависимостей от репозиториев или dao, только преобразование уже полученных где-то ранее (в сервисе) объектов

2023-11-30 12:47 UTC, VadimZharkov commented
По тестам хорошо все проработал, в мок тестах довольно часто используют конструкцию verify. Попробуй ее применить  в нескольких тестах.

2023-11-30 12:47 UTC, VadimZharkov requested changes
Можно улучшить

2023-12-01 23:00 UTC, tarasovEgor commented on src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
> +            if (size == 2) size = 1;
Добавил 126 строку как вынужденную меру, единственная проверка (/bookings?from=4&size=2), которая не проходила, очень долго с ней сидел так и не понял, как исправить. Проверка не проходила только из-за того, что при size = 2 возвращался пустой список, с другими значениями и в аналогичных методах (getAllBookingsByItemOwner) все работало хорошо.

2023-12-01 23:11 UTC, tarasovEgor commented
Привет! Переписал методы - getAllBookingsByBooker/getAllBookingsByItemOwner (BookingServiceImpl), добавил обработку статуса 500 в ErrorHandler, несколько проверок с конструкцией verfiy. Закомментированные классы убрал, надеюсь теперь лучше выглядит.

2023-12-02 11:17 UTC, VadimZharkov approved these changes

2023-12-05 20:34 UTC, merged