feat: add docker
tarasovEgor/java-shareit pull request #4
Opened 2023-12-11 15:33 UTC by tarasovEgor

2023-12-13 20:29 UTC, tarasovEgor commented
Привет, так и не смог пройти несколько проверок на гите, по какой-то причине запросы на GET:
        - /items/id
        - /bookings?state=WAITING
        - /bookings/owner?state=WAITING
        - /bookings?state=REJECTED
        - /bookings/owner?state=REJECTED
Валятся с ошибкой:
        {"error":"could not extract ResultSet; SQL [n/a];
         nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet"}
При локальном запуске тестов на базе H2 через postman проблем не возникает, все проверки проходят, очень долго пытался найти решение, так и не получилось. Наставник в Пачке ничего не говорит, советов дельных нет, пробовал дебажить по сто раз, переписывал модели в gateway и логику валидации, тоже особо не прояснило ситуации, в общем я в отчаянии :)

2023-12-14 07:34 UTC, VadimZharkov commented
> ![postman_tests](https://private-user-images.githubusercontent.com/126291914/290321356-c5fcb457-cd36-4d07-a691-8af629bf22e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Mzc5MTMsIm5iZiI6MTcwMjUzNzYxMywicGF0aCI6Ii8xMjYyOTE5MTQvMjkwMzIxMzU2LWM1ZmNiNDU3LWNkMzYtNGQwNy1hNjkxLThhZjYyOWJmMjJlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwNzA2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Nzc2ZmViMmNlMmJmYWFkMTAwYzI5NGVkNTQ1MjI3NTA0MTM0N2Q4MWVhMzI3OWUwYjlmZWE5YzliYzkwZjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IHR4POGgKjl6WGy-0BkGa_i05G1bDYnccN2nEcdQe_c) Привет, так и не смог пройти несколько проверок на гите, по какой-то причине запросы на GET: - /items/id - /bookings?state=WAITING - /bookings/owner?state=WAITING - /bookings?state=REJECTED - /bookings/owner?state=REJECTED Валятся с ошибкой: {"error":"could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet"} При локальном запуске тестов на базе H2 через postman проблем не возникает, все проверки проходят, очень долго пытался найти решение, так и не получилось. Наставник в Пачке ничего не говорит, советов дельных нет, никто не знает что это такое, в интернете тоже не много инфы по данной ошибке, пробовал дебажить огромное количество раз, переписывал модели в gateway и логику валидации, тоже особо не прояснило ситуации, в общем я в отчаянии :)

Привет, эта ошибка говорит, что сгенеренный спрингом sql не нравится СУБД.
H2 отличается от PG, не все один в один при смене БД будет работать.
Возможно есть несоответствие в названии полей сущностей и колонок базы.
Предлагаю в application.properties подкдючить расширенное логгирование сгенеренных sql запросов и посмотреть их и позапускать их руками. Раз на Get падает, то это будут select-ы.
Статья  про логгирование https://www.baeldung.com/sql-logging-spring-boot

И еще можно поупрощать, убрать например SEQUENCE и сделать просто SERIAL

2023-12-14 07:38 UTC, VadimZharkov requested changes
Предлагаю добавить трассировку sql запросов для понимания в чем причина

2023-12-14 19:44 UTC, tarasovEgor commented
Добавил трассировку в логах при GET /items/id вылетает следующая ошибка: 
![sql_error](https://github.com/tarasovEgor/java-shareit/assets/126291914/835b6590-2e38-46e8-8dec-c41fd60723ce)

2023-12-14 19:48 UTC, tarasovEgor commented
Насколько я понимаю скорее всего связано с enum-типом в таблице bookings, ошибка в приведении типов. Но тогда странно, что остальные проверки, например, GET /bookings?state=FUTURE проходят без проблем
![error_enum](https://github.com/tarasovEgor/java-shareit/assets/126291914/44c38f82-1cc0-42b7-ae19-a36b29bb33bd)

2023-12-14 22:59 UTC, tarasovEgor commented
Да, все-таки ошибка связана с enum-типом - BookingStatus, сначала переписал методы BookingRepository, чтобы на вход вместо типа BookingStatus приходила строка, но пришла как-раз таки ошибка со скрина: ![bookingstatus](https://github.com/tarasovEgor/java-shareit/assets/126291914/dff7a16b-74d1-401c-957b-0f966ba2ac00),
потом попытался создать новый тип и cast в schema.sql, как показано в этой статье: https://www.schakko.de/2020/06/28/how-to-fix-psqlexception-error-operator-does-not-exist-character-varying-in-spring-jdbc-and-spring-data-jdbc/ 
![image](https://github.com/tarasovEgor/java-shareit/assets/126291914/a10353c7-4578-461b-8fd9-94e4c8f9631b)
но при запуске все валится с очередной ошибкой:
![image](https://github.com/tarasovEgor/java-shareit/assets/126291914/6400ef66-2496-4a3b-8436-eb44a0fca675)
Думал еще просто изменить тип поля status в Booking и всех dto на строку, но думаю так было бы не совсем корректно делать да и вообще придется все методы переписывать, убрал sequence еще, никак не повлияло вообще, может есть еще какой-нибудь способ привести типы или создать новые в schema.sql? Идеи пока что кончились

2023-12-15 17:26 UTC, tarasovEgor commented
Удалось наконец-таки пройти, добавил аннотацию @Enumerated(EnumType.STRING) в модель Booking, проблема решилась)

2023-12-16 06:43 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/booking/service/impl/BookingServiceImpl.java
По ТЗ валидацией входных данных у нас теперь занимается gateway, поэтому все конструкции вида
```
  if (bookingDto.getStart() == null || bookingDto.getEnd() == null) {
            throw new InvalidBookingDateException("Invalid booking date.");
  }
```
нужно вынести gateway

2023-12-16 06:44 UTC, VadimZharkov commented on server/pom.xml
> +        <dependency>
Т.к. валидация в gateway то данная зависимость здесь уже должна быть не нужна

2023-12-16 06:48 UTC, VadimZharkov requested changes
Отлично проработал поиск ошибки (в жизни все примерно так и происходит))

По ТЗ валидацию входных данных нужно вынести в gateway. Это ручные проверки, проверки с помощью аннотаций и соответственно зависимости в pom. Нужно доделать.

2023-12-17 08:18 UTC, VadimZharkov approved these changes

2023-12-18 19:41 UTC, merged